default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: clock_in_out_application_development
  username: postgres

test:
  <<: *default
  host: localhost
  database: clock_in_out_application_test
  username: postgres

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
